# Eleven v4 performance direction for every FTUE line. Tags go before the words they colour and
# carry forward until the next tag; one emotion per phrase. Text after the tags must equal the
# approved line (checked by gen_ftue.py), so only delivery changes, never wording.
TAGGED = {
 "home":        "[warm, welcoming] Recruit, this is Nightfin. [calm, confident] You're cleared for your first deployment. [softly encouraging] Hit Play when you're ready.",
 "home_nudge":  "[dry, amused] It's the big button, Recruit. [pause] The one that says Play.",
 "move":        "[calm, focused] Drag anywhere to move. Your gun fires on its own. [reassuring] Just stay alive.",
 "move_nudge":  "[firm, slightly urgent] Keep moving, Recruit. [serious] Standing still is how they get you.",
 "move_done":   "[pleased, a small smile] That's it. You're a natural.",
 "xp":          "[excited] First kill! [playful] See the bar up top? That's your XP!",
 "xp_done":     "[cheerful, speedy] Fill the bar, you level up! [playful] Easy, right?",
 "card":        "[calm, firm] Level up. Pick one card. [slowly] No timer this time. [thoughtful] Think.",
 "card_done":   "[matter-of-fact, like a coach] One card each level. Six skills. Four stats. [content] Then rank them up.",
 "relay":       "[softly] That's a signal relay. [pause] [calm, quietly] Stand in the ring for twelve seconds. I'll handle the rest.",
 "relay_out":   "[gentle] You stepped out. [pause] [reassuring, softly] It's okay, it drains slowly. Hop back in.",
 "relay_done":  "[quietly satisfied] Uplink's up. [pause] HQ sent you a card. Pick one.",
 "cache":       "[curious, delighted] Ooh, a supply cache. [warm] Stand on the pad, pay a few coins, and pick a card.",
 "cache_poor":  "[sweet, sympathetic] Not quite enough coins yet, sweetie. [encouraging] Come back after a few more kills.",
 "cache_done":  "[playful, wise] The price goes up every time you buy. [gentle teasing] Spend it wisely, okay?",
 "beacon":      "[excited] Boss beacon! [thrilled] Step in and an Alpha comes for you! [suddenly serious] Only if you're ready!",
 "beacon_go":   "[rushed, excited] Here it comes! [shouts] Keep moving, keep moving!",
 "beacon_kill": "[calm, proud] Alpha down. [warm] That's a first for you. [businesslike] Go grab the chest it dropped.",
 "drop":        "[cheerful] Drop incoming. [helpful] Stand next to the pod for a second to open it.",
 "drop_done":   "[content, proud] Coins and a little something extra. [sweetly] I packed it myself.",
 "heal":        "[calm, caring] Med station. [pause] Stand in it to switch it on, then stay inside.",
 "heal_done":   "[softly] It's healing you now. [pause] Eight seconds. [quietly worried] Don't wander off.",
 "hurt":        "[gasps] [worried] Oh, you're hurt. [caring] Look for a med station, sweetie. [reassuring] Green light, you can't miss it.",
 "magnet":      "[delighted] Ooh, a magnet. [amazed] Every coin on the map is flying to you.",
 "bomb":        "[excited] Bomb! [shouts] Boom! [proud] Everything on screen, gone! [pause] [deflated] Elites... less gone.",
 "freeze":      "[calm, precise] Freeze clock. [pause] Four seconds. [quietly encouraging] Make them count.",
 "chest":       "[calm, instructive] First chest. Rank a power to five. Own its partner card. [slowly] The next chest evolves it.",
 "chest_claim": "[gentle, almost warm] Claim it. No rush this time.",
 "revive":      "[steady, reassuring] You're down, Recruit. [warm] The first one's on HQ. [firm] Get back up.",
 "revive_done": "[relieved, dry] There you are. [amused] Let's not make that a habit.",
 "result":      "[sympathetic, calm] The horde got you. [thoughtful] It gets everyone, eventually. [proud, warm] That was good work for day one.",
 "result_gift": "[sweet, generous] I topped you up to four hundred coins. [playful] Go say hi to Lukas, he's been waiting.",
 "gun":         "[impatient, excited] Finally! [proud] Makarov. Hits harder, shoots faster than that sad little pistol. [insistent] You have the coins. Buy her!",
 "gun_done":    "[proud, overjoyed] Ja! Now you have a real gun. [fatherly, stern] Be nice to her!",
 "gun_leave":   "[startled] Wait, wait! [outraged] You're leaving? With all those coins? [shouts] Nein!",
 "daily":       "[warm] Daily gifts are open now. [sweetly] Come by every day, I'll always have something for you.",
 "lv2":         "[firm, like a coach] Level two. Missions are open. Clear them. Earn Pass rewards. [serious] Every day.",
 "lv2_done":    "[flat, stern] Three missions. No excuses.",
 "lv3":         "[happy] Level three. [warm, generous] The supply crates are open, and your first pull is on me.",
 "lv3_done":    "[curious] Ooh, let me see. [helpful] Oh, and doubles turn into shards, so nothing goes to waste.",
 "lv5":         "[excited] Level five! Gun stars! [speedy] Shards and coins go in, damage comes out! [shouts] Wunderbar!",
 "lv5_done":    "[amazed] One more star! Look at her shine! [sniffs] [trying not to cry] I'm not crying. Gun oil.",
 "graduate":    "[proud, warm] That's basic training done, Recruit. [thoughtful] From here on, it's you and the horde. [calm] Nightfin out.",
}
